### ISSUE TITLE
The connector desent seems to be working when there is no payload provided. 

### ISSUE THREAD

**Issue by Kamidu** [wso2-extensions/esb-connector-slack#4]
**Description:**
Even if the correct values are provided via the parameters as fro the template, it will not read the data from the params but allways try to check the payload for the content. 

**Suggested Labels:**
Bug, Critical

**Steps to reproduce:**
Create a sequence to read the values from headers and parse as a parameter and invoke the sequence without any data in the body.

**Comment by anupama-pathirage** [comment]
Moved the isseu https://github.com/wso2/micro-integrator/issues/3517
